name: pip_services3_commons
version: "1.1.0"
description: Common patterns for Pip.Services in Dart. This framework is part of the [Pip.Services](https://github.com/pip-services/pip-services) project.
homepage: https://github.com/pip-services3-dart/pip-services3-commons-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  uuid: ^3.0.4
  analyzer: ^2.2.0

dev_dependencies:
  test: ^1.17.12