FROM google/dart

# Set a working directory
WORKDIR /app

# Copy the entire project
COPY . .

RUN pub global activate dartdoc

# Generating docs
RUN dartdoc --no-auto-include-dependencies --no-include-source --show-progress
