// /** @module validate */

// /** 
//  * Types of validation results generated by validation schemas. 
//  * 
//  * @see [[ValidationResult]]
//  */
// export enum ValidationResultType {
//     /** General information (not an error). */
//     Information = 0,
//     /** Warning about something suspecious. In strict mode is treated as error */
//     Warning = 1,
//     /** Validation error. */
//     Error = 2
// }