import './ValidationResultType.dart';

/**
 * Result generated by schema validation
 */
class ValidationResult {
  String _path;
  ValidationResultType _type;
  String _code;
  String _message;
  dynamic _expected;
  dynamic _actual;

  /**
     * Creates a new instance of validation ressult and sets its values.
     * 
     * @param path      a dot notation path of the validated element.
     * @param type      a type of the validation result: Information, Warning, or Error.
     * @param code      an error code.
     * @param message   a human readable message.
     * @param expected  an value expected by schema validation.
     * @param actual    an actual value found by schema validation.
     * 
     * @see [[ValidationResultType]]
     */
  ValidationResult(
      [String path = null,
      ValidationResultType type = null,
      String code = null,
      String message = null,
      dynamic expected = null,
      dynamic actual = null]) {
    this._path = path;
    this._type = type;
    this._code = code;
    this._message = message;
    this._expected = expected;
    this._actual = actual;
  }

  /** 
     * Gets dot notation path of the validated element.
     * 
     * @returns the path of the validated element.
     */
  String getPath() {
    return this._path;
  }

  /** 
     * Gets the type of the validation result: Information, Warning, or Error.
     * 
     * @returns the type of the validation result.
     * 
     * @see [[ValidationResultType]]
     */
  ValidationResultType getType() {
    return this._type;
  }

  /**
     * Gets the error code.
     * 
     * @returns the error code
     */
  String getCode() {
    return this._code;
  }

  /**
     * Gets the human readable message.
     * 
     * @returns the result message.
     */
  String getMessage() {
    return this._message;
  }

  /**
     * Gets the value expected by schema validation.
     * 
     * @returns the expected value.
     */
  dynamic getExpected() {
    return this._expected;
  }

  /**
     * Gets the actual value found by schema validation.
     * 
     * @returns the actual value.
     */
  dynamic getActual() {
    return this._actual;
  }
}
